witheve/Eve

- readme.md
I tried building this on rust stable and it failed due to the use of feature gates.
> Use rust nightly

- runtime/src/bin/map.rs
- runtime/src/bin/migrate.rs
This pull request does two things:
1. It fixes all warnings in regular, test, and benchmark mode.
2. It updates map.rs to use the 'tests module' pattern, which is
considered idiomatic.
> Fix warnings & improve idioms

- tutorials/intro tutorial/tutorial.html
> correct misspelling in tutorial

- ui/css/editor.css
> Move modals above geometric center; make position independent of height

- ui/css/editor.css
quick fix so that editor form is visible
> fixes #286 - expands form container to 100% height so it is visible

- tutorials/intro tutorial/tutorial.html
If this is not the right place to fix these links please point me in the direction.
> Point tutorial links to right places

- css/renderer.css
- renderer.html
- server/examples/ci-tool.e
- server/src/server/exec.clj
This lays the groundwork for the visual aspect of the CI tool. It includes some basic css and richer information than the previous proof of concept.
> CI Tool UI

- index.html
Fix a typo in index.html introduced in commit fad4a7fb361f0d95558d8848861cd5e737c79c81
> Fix typo: basckground -> background

- README.md
> Missing `run` in docker cmd

- src/client.ts
- src/runtime/databases/http.ts
- src/runtime/providers/string.ts
- src/runtime/server.ts
I had the need for some more features, while implementing an OpenID Connect Client in Eve.
**About the client:**
The current state & implementation for the OIDC client can be found here:
https://gist.github.com/renegr/0dbc9b05efc4d7305fd1764770e3059d
The actual lines of code needed to implement an OIDC Client in Eve is surprisingly small 👍 
**About the pull request**
The code works, but I am not so sure if the implementation for urlencode is "proper Eve" ;)
> Support for query-params; New String Function: urlencode; @http bugfix

- src/runtime/providers/math.ts
For issuehttps://github.com/witheve/Eve/issues/523
> Correct Pow function having arguments inverted.

- README.md
- src/runtime/databases/node/server.ts
- src/runtime/server.ts
Was looking into how to add database/providers on serverside, and the closest example didn't quite work :)
> Fix HTTP server example

- Dockerfile
- README.md
The user was previously root, which was causing the install to fail.
> Set user in Docker container to complete install

- examples/CRM.eve
The fake times in test data were causing problems with ordering in conjunction with messages with real times.
> Fix CRM app

- examples/CRM.eve
Fix dead link to quickstart tutorial
> Fix dead link in CRM.eve

- src/renderer.ts
> fix dom ordering when sort is 0

- css/ide.css
- src/client.ts
- src/ide.ts
Fixes https://github.com/witheve/Eve/issues/546
> Disconnect notification

- src/runtime/providers/math.ts
- test/math.ts
After the mess the previous pull got into, recreate and send again.
> Resolve NaN issue, with tests.

- examples/tic-tac-toe.eve
Raised in docs issue 36: https://github.com/witheve/docs/issues/36
> Fix typo in TicTacToe

- package.json
- src/runtime/parser.ts
The **"rule"** helper was inserted into Chevrotain.
https://github.com/SAP/chevrotain/issues/316
> Update Parser Rule Definition Syntax.

- index.html
- src/client.ts
- src/loadWorker.js
- src/runtime/eveSource.ts
- src/runtime/server.ts
- src/runtime/webworker.ts
- src/systemJSConfig.js
This gets the runtime working in a webworker. As part of this we fixed the feature detection for loading files in eveSource and also pulled the SystemJS config out of index.html and put it into its own js file.
> get eve running in a webworker

- src/runtime/databases/node/http.ts
> don't allow bad responses to flow through the http code for node

- src/renderer.ts
Added handlers for mousedown & mouseup
> Handle mousedown & mouseup events

- examples/event.eve
Addition of the mousedown and mouseup to renderer.ts needs a change to the event.eve file to clear them after one tick.
> Ensure mousedown and mouseup events are cleared.

- examples/gaussian.eve
- src/runtime/providers/math.ts
- test/math.ts
For https://github.com/witheve/Eve/issues/739
Once in I'll also post a change notice to the news-group.
Regards,
Cormac.
> Rename Gaussian Attributes to not use Unicode.

- src/runtime/runtime.ts
This lays out the interfaces for Constraints (which will be Scans, FunctionConstrains, Choose, Not, etc) and Indexes. Using the `Constraint` and `Index` interfaces we implemented generic join in JoinNode as well as a very simple ListIndex.
> Generic join, function constraints, really bad indexes

- src/runtime/runtime.ts
Provisional InputNode (doesn't actually commit yet) and a simple Block abstraction.
> Add InsertNode and Block wrapper

- index.html
- src/runtime/indexes.ts
- src/runtime/runtime.ts
- src/systemJSConfig.js
I goofed and merged the previous PR into the wrong base. #754
> Refactor runtime performance

- src/runtime/runtime.ts
General cleanup and documentation pass to make following along with the refactor easier for the community.
This is just a first pass, but I wanted to make sure there was enough structure and documentation to the code for the intrepid to get the gist of what's going on.
> Refactor reorganize sections

- src/runtime/builder.ts
- src/runtime/errors.ts
- test/math.ts
- test/strings.ts
For https://github.com/witheve/Eve/issues/670
> Fix for 670, handle undefined attribute mapping.

- src/runtime/runtime.ts
Actually merge this into the right branch. #758
> Refactor runtime interner release

- src/runtime/dsl.ts
- test/foundation.ts
- test/performance.ts
…of the individual useful methods.
This is useful for the subblock case and for bringing new things into scope without having to edit every test.
> DSL functions take a block instead

- src/runtime/dsl.ts
- test/foundation.ts
Not won't work until we actually add not to the runtime and emit NotNodes, but this paves the way for testing that.
> Add subblock and not support to the DSL

- src/runtime/dsl.ts
- src/runtime/indexes.ts
- src/runtime/runtime.ts
This converts most of the runtime to user iterators instead of resetting arays
> Iterators for array reuse

- src/runtime/dsl.ts
- src/runtime/runtime.ts
- test/foundation.ts
This change adds both choose and union nodes, as well as hooking choose and union up in the dsl. Still need to add comments about how the flows I added here work as there are some subtleties that need to be documented.
> Choose and union!

- assets/css/base.css
- package.json
- src/bootstrap.ts
- src/programs/flappy.ts
- src/programs/perfReport.ts
- src/runtime/dsl2.ts
- src/runtime/indexes.ts
- src/runtime/performance.ts
- src/runtime/runtime.ts
- src/runtime/stdlib.ts
- src/systemJSConfig.js
- src/types.d.ts
- src/watchers/dom.ts
- src/watchers/ui.ts
This includes a bunch of performance fixes to get flappy sailing at 60fps.
> Runtime performance

- src/runtime/runtime.ts
- test/choose.ts
Choose only antijoined with the previous branch, but it actually needs to antijoin with every result from the branches above it.
> add a test for choose with more than 2 branches, fix that case

- src/programs/compiler.ts
- src/watchers/compiler.ts
add lookup to the compiler watcher
> add lookup

- src/bootstrap.ts
- src/programs/compiler.ts
- src/runtime/dsl2.ts
- src/watchers/compiler.ts
allow adding to existing records and add in remove outputs
> Runtime compiler remove

- src/runtime/dsl2.ts
- src/runtime/runtime.ts
- src/runtime/trace.ts
- test/aggregate.ts
- test/choose.ts
simplify results ownership, add AggregateOuterLookup node, get all the aggs in chooses tests passing
> Fix aggregates in choose

- package.json
- src/index.ts
- src/watchers/watcher.ts
* package.json cleanup
* version bump
* remove outdated magic watcher inclusion logic
> Refactor runtime

- src/programs/perfReport.ts
its not ready for external use.
> move the perf reporter demo back into the runtime.

- src/programs/perfReport.ts
- src/runtime/dsl2.ts
- src/watchers/dom.ts
- src/watchers/editor.ts
- src/watchers/system.ts
- src/watchers/tag-browser.ts
- src/watchers/ui.ts
- src/watchers/watcher.ts
> Refactor/rename inputEAVs

- src/programs/perfReport.ts
- src/runtime/dsl2.ts
- src/watchers/canvas.ts
- src/watchers/dom.ts
- src/watchers/editor.ts
- src/watchers/html.ts
- src/watchers/shape.ts
- src/watchers/tag-browser.ts
- src/watchers/ui.ts
- test/aggregate.ts
- test/antijoin.ts
- test/choose.ts
- test/foundation.ts
- test/performance.ts
- test/union.ts
Matches the old syntax better, and is more in line with the other output methods `commit` and `watch`
> Rename Program.block -> Program.bind

- test/aggregate.ts
@shamrin recommended that we add a test case showing how limits work using aggregates.
@shamrin the GH UI doesn't let me request a review from non-maintainers, but please look this over and let me know if it's in line with what you expected.
> Add limit test

- examples/quickstart.eve
> Release v0.2.5
