run.sh

On my system, run.sh doesn't work, becuase opening the browser blocks
the server from getting started. Adding a & backgrounds the open.

Run the commands in the background.

---

run.sh

The installation instruction does not currently match the actual script name. This resolves it so users can copy & paste command.

Fix install instruction to match actual file name

---

ui/css/editor.css

Currently, the "New" and "Import" buttons in the welcome message show above the searcher, if they should overlap.  This seems to be because both the buttons and the searcher are given a z-index of 10 and the buttons show up later in the DOM.  I'm guessing that there's a reason the buttons must have the z-index they do, so I've upped the z-index of the searcher-container to ensure it's comfortably over the buttons.

Ensure the searcher has a larger z-index than welcome buttons

---

ui/css/editor.css
ui/src/editor.ts

This commit addresses issue #169, by reusing the existing .button class to style this button.
Some potential issues you may want to consider:
- In order to limit the width of the button, I had to add a parent to act as a container.  Maybe there's a better way to do this, but I'm not that familiar with the flexbox model.  (We could do it by not using flex, but it looks like you're trying to stick with flexbox everywhere.)
- The default button styling doesn't work so well against the lighter background of the form, so I copied the styles from the modal dialog for these buttons as well.  These rules are in their own section, but I'm using two selectors to pick out the two cases.  Perhaps the form and modal dialog should share a "light background" class?  Or maybe we don't want these buttons …

Style the table "Submit" button to look like a button

---

ui/src/tableEditor.ts

This follows the suggestion in #232, which seems sensible to me.

Force to string before using localeCompare

---

ui/src/editor.ts

The existing import code changed all falsey values to empty string.  It looks like we need to do that to undefined, but other values, like 0 or false, should be let through as-is.
This was reported in #242.

Allow importing falsey values from CSV

---

ui/css/editor.css
ui/src/editor.ts

I have trouble reading the buttons that stretch all the way across a pane as buttons.  They look much more like text areas to me.  Letting them take a natural width is enough to make them look like buttons.  Maybe I'm just weird, but here's a patch to change that, in case it bothers other people too.
This patch targets specific buttons with relatively specific CSS selectors.  We could get the same effect, as of now, by settings `align-self: flex-start` on all `.button`s.  This might give us undesired results if buttons of different natural heights are in a horizontal container.  I don't know if that's something we should worry about or not.
I also snuck in a change in capitalization of a button label.

Keep buttons from stretching to fill width of parent

---

run.sh

Clean up the following in run.sh:
* Fix shellcheck warnings.
* Switch to #!/usr/bin/env bash to use the current environment's bash.
* Parse command line flags.
* Add help message.
* Use for loop to dry code up when checking dependencies.
* Send pushd and popd stdout and stderr to /dev/null to declutter script output.
* Check multirust list-toolchains for existing install before overriding.
* Store multirust version in a variable.
Minor:
* Reword a few sentences.

Clean up run.sh

---

ui/src/editor.ts

To address #252.
A few potential issues:
- Performance on Firefox can be poor, with the post-render step taking 35-40 ms.  This doesn't seem to be a problem in Chrome.  I don't understand the difference.
- If a tooltip runs off the bottom, it gets moved to align with the bottom.  Perhaps it should be moved a bit further so the drop shadow is visible?
- Only vertical position is considered.  Should we also worry about these running off the right of the screen?  This would require a bit more logic to avoid drawing the tooltip over top of the button.
- I only trigger this for things created by "showButtonTooltip".  Perhaps it should happen for everything created by "showTooltip"?  I don't understand the distinction between these two things.

Move tooltips vertically to keep entirely on screen

---

design/language.md

The words `we treat` are duplicated.

Fix typo in language.md

---

build/Makefile

The `build/Makefile` changed in a way that prevents top-level `Makefile' from running

Fix relative paths in build/Makefile

---

src/runtime/providers/math.ts

I have implemented range[] so I can update my Eve programs to work with the ts-merge branch. I think I've implemented the correct behaviour for here. I used the following program plus adding some trace to manually check it works.
```
commit
[#birthday age: -2]
[#birthday age: 3]
[#birthday age: 8]
[#birthday age: 13]
[#birthday age: 18]
[#birthday age: 20]
[#birthday age: 21]
[#birthday age: 23]
[#birthday age: 30]
[#birthday age: 30]
[#birthday age: 40]
[#birthday age: 42]
[#birthday age: 60]
[#birthday age: 64]
```
```
search
birthday = [#birthday not(cake-type)]
commit
birthday.cake-type := "normal"
```
```
search
birthday = [#birthday cake-type age]
age = range[from: 1 to: 12]
commit
birthday.cake-type := "special"
```
```
search
birthday = [#birthday cake-type age]
age = range[from: …
```

Implement range[from? to? increment? return]

---

examples/tic-tac-toe.eve

Noticed that the language - and the code - was exactly backwards for this calculation (yay narrative), fixed it.

Correct anti-diagonal scoring in tic-tac-toe example

---

package.json

Fixes the npm warnings when you npm install, saying no license or repository fields

Add License and Repository fields, fixes annoying npm warnings

---

src/runtime/databases/http.ts
src/runtime/databases/node/http.ts
src/runtime/databases/node/server.ts

Fixes #483.
Aside: Typescript should've caught these errors but didn't, so maybe there's something wrong with the project configuration?

Add node id to InsertAction constructor calls.

---

examples/event.eve
examples/form-binding.eve
src/renderer.ts

Note that the change event deviates from the DOM change event for radio buttons since it fires on both the newly selected radio box and the old, automatically unselected radio box. This is to make it easier to sync the browser from it.

Add tickbox change event, propagate to records & add illustrative example

---

examples/clock.eve
examples/inspector.eve
src/runtime/providers/math.ts
src/runtime/util/deprecated.ts
test/join.ts
tsconfig.json

This pull request is to fix #513 .

Replace angle with radians and degrees in sin and cos

---

src/client.ts
src/ide.ts
src/runtime/runtimeClient.ts

Merging the client refactoring broke the inspector logic on local runtimes. The client was in some cases double-stringifying message payloads, resulting in failure to interpret some messages in the language service.

Fix inspector

---

src/client.ts
src/runtime/runtimeClient.ts

The "ping" message was causing the server to crash because it isn't an object.

all messages to the server should be an object

---

src/runtime/server.ts

Displays a better message when the server stops, and a better error when the server cannot start due to the port being in use.

Better messages for Eve server

---

src/renderer.ts

The datalist tag is a HTML5 tag that allows you to specify autocomplete options for input fields. I needed it for something I'm developing, and there doesn't seem to be a reason for excluding it.

Added datalist tag to supported HTML tags.

---

src/renderer.ts

Whenever changing an input's value, the cursor is reset to the end of the input. Not noticable unless you try to change something in an input value that is not at the end.
With the following Eve program:
```eve
commit @browser
[#input]
```
Fill in the input with a string. Move the cursor to the beginning of the string (or anywhere not at the end). Write something. You'll see that it's impossible to add something without the cursor resetting to the end of the string.
The solution is actually very simple, and hinted at in `renderer.ts`, simply use setAttribute instead of setting the input value directly.

Fixed cursor reset when changing value of input.

---

src/runtime/util/eavs.ts
test/eavs.ts

Fixes #478 by adding a sentinel value for nulls in JSON. Also added a test to ensure that nulls in objects and arrays roundtrip correctly.
This is a followup to #593

Add a sentinel value for nulls in JSON

---

src/runtime/join.ts
test/join.ts

Currently nots that have no dependencies never get an opportunity to run since they are never solving for a variable. This PR adds a prejoin flag to accept and changes NotScan to force an accept check in the case when prejoin is true and the scan has no args. It also adds an extra step to the preJoinAccept function to check nots if they would otherwise not be.

Fix not without dependencies

---

src/runtime/block.ts

Ifs and nots can technically use only local variables and don't necessarily mean we have database scans. The practical implication of this is that any block that had an if or not in it always reran when evaling. This prevents purely static blocks from doing so.

Fix determining if a stratum has database scans

---

src/runtime/parser.ts

The second argument (boolean) to the constructor of a Chevrotain Lexer
should not be used in most productive flows.
It effectivily disables the validations performed on the Lexer.
For example:
* Finding duplicate patterns.
* Using Lexer Modes which have not been defined.
* and more...
This boolean argument defers the handling of the errors instead of just throwing an error.
This incorrect usage must have been copied / pasted from an example in the Chevrotain online playground
(Where the defering is used to display errors in the UI).

Fix Chevrotain Lexer Initialization.

---

src/runtime/runtime.ts

This is necessary to make my Minesweeper example work for larger sizes. In the current version mine placement takes n*mines rounds to coalesce where n is some small factor n=1..3. I don't know if there's the possibility of a more principled or better approach for this longer term (eg maybe this could be configurable somehow and the default could be 30) but I think a larger value might be good to tide things over until this is decided on.

Increase MAX_ROUNDS 30 => 300

---

css/ide.css
src/client.ts
src/ide.ts

Reported by @convolvatron, not all calls to `ide.injectNotice` were guarded to ensure that we were running in editor mode. Rather than voiding those messages (as we were in other places) we now shunt them to the console. In the long term we should display them in-browser, but it's an open question as to how to do that without destroying the user-content below. Likely routes include an error modal or an overlay shade.

Wrap clients injectNotice calls to make it editor-agnostic

---

src/runtime/builder.ts
src/runtime/errors.ts
test/join.ts

Example
```
search
lookup[]
```
Will produce error
```
Searching a lookup requires at least one of record, attribute, value, or node to be present
```
_(text may need a proofreading, since I'm not a native English speaker)_
I'll probably send another PR tomorrow to fix `lookup` to work with partially missing variables (related  https://github.com/witheve/Eve/pull/611#issuecomment-263498342).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/619)

Blank lookup in a search should produce error

---

src/runtime/join.ts

There are two reasons to remove this condition.
1. It's not used. All conditions when `attribute` is present are
already coverered via index lookup in other branches of switch in `getProposal`
(`*a**`,`ea**`,`*av**`,`eav*`,`***n`).
2. It's broken. Default branch of switch (which corresponds to full scan) in
`getProposal` always populates `providing` in order of EAV, but if this
condition would ever run it would return values in order of AVE thus
breaking the assumptions of `joinRound` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/611)

Remove unnecessary condition in fullScan

---

src/ide.ts

When saving to the file system, localStorage is not updated. Unfortunately, since localStorage (and failing that, the fileCache) was used as the source of truth on the client, work would appear to be lost until a hard refresh, and would actually be lost if any edits were made prior to refreshing.
The fix here is fragile, and doesn't handle the case where the user has existing localStorage saves for the file or the case where the user edits in the editor, then the file system, then the editor again without a refresh in between, but it at least fixes the particular case in #586.
A more durable fix will arrive along with the client refactoring work.

quick fix for #586. A more durable solution is inbound

---

examples/todomvc.eve

The comment is now consistent with both [todomvc spec][1] and the code (except for bug #607). Blur and enter should both commit the change, escape should cancel it.
[1]: https://github.com/tastejs/todomvc/blob/master/app-spec.md

fix todomvc comment: blur & enter commit, escape cancels

---

test/join.ts
test/math.ts
test/shared_functions.ts

Just changed some formatting in tests to make more consistent

Format tests

---

src/runtime/providers/math.ts
test/math.ts

The Gaussian provider uses different keys when reading and writing into the internal cache, so it violates referential transparency as describe here: https://gist.github.com/joshuafcole/52f706e0e838b3fb7536814de8879af0.

Fix a bug in "gaussian" function

---

src/runtime/providers/sort.ts

This was a copy-pasta mistake when porting sort from other aggregates. Unlike a normal aggregate which only needs to lookup the result based on group, each value in the group of a sort has an index that needs to be looked up.
This fixes [this issue](https://groups.google.com/forum/#!topic/eve-talk/stC-znRyUQE) reported on the mailing list.

fix sort.test() not correctly looking up results

---

src/ide.ts

Hello, you wonderful Eve people!
As I started working on my first Eve project, I noticed something odd. Code blocks that looked fine in the browser IDE were saved to disk with odd indentation inconsistencies. [Here's an example](https://github.com/asolove/Eve/pull/3/files#diff-0a7fde0cf8bef01cdfe0772e72e41d2bR47): 
It turns out that when the editor automatically indents inside code blocks, it adds a soft tab of two spaces. But when the user hits the tab key, CodeMirror was adding a literal tab and displaying it with a width of two spaces. So when the code is saved to disk, some lines are indented two spaces (if they came from auto-indent) and some were indented with tabs (because I indented them)
Luckily there's a [length conversation about soft …

When user types tab, translate it into spaces for consistency

---

examples/join.eve
src/runtime/providers/aggregate.ts
test/all.ts
test/shared_functions.ts
test/strings.ts

This version allows for separator to be a set, but doesn't put a separator at the beginning or end of the result string

implement aggregate join by overriding the whole aggregate() method.

---

src/runtime/builder.ts
test/join.ts

The issue in #649 was caused by a set of issues. First, the maybeLevel function had bugs in it that caused us to look at the wrong scan to determine the minimum level for a variable. Second, we were automatically setting the returns of an aggregate to the same level as the aggregate itself, which is incorrect in the case where there are other providers for a variable (e.g. a database scan).
To fix this, I fixed the bugs in maybeLevel and then instead of blanket setting all returns of aggs to the aggs' level, I do a pass to check for the minimum level that could provide that var and set it to that.
Fixes #649.

Fix stratification when joining aggregate results with other scans

---

src/runtime/providers/math.ts
test/math.ts

Mentioned as missing in https://github.com/witheve/docs/issues/46

Add Fix function.

---

src/runtime/block.ts

Very strange symptoms are caused by this mistake which would prevent some blocks from running even when changes should've made them do so. Any block that looked for an attribute with a fixed value on a record with no tags would be skipped since `attr` cannot be both `true` and an object at the same time :(

Fix DependencyChecker if branch that looks at attributes with a fixed value

---

src/runtime/parser.ts
test/join.ts

In code where sub-records were defined in a parenthesis, we weren't pushing the parent's identity down into the children, we also weren't setting `eve-auto-index` on them. This makes sure we do both and should remove any differences between using parens or not.
Fixes. #673

Make sure records in parenthesis are treated the same

---

test/join.ts

A `test.only(` got checked in, which means only one of the tests are currently running.

get all the tests running again, fix a broken one

---

src/runtime/parser.ts
src/runtime/providers/logical.ts
src/runtime/providers/string.ts

There are a few functions that aren't meant for end-users that the runtime itself uses. This PR renames those and adds comments to make that clearer so people don't waste their time trying to get them to work.

mark a few providers as being internal

---

src/runtime/join.ts

There is no point in checking the rest of proposal providers after a proposal with zero cardinality was returned.
I could have `return`ed directly instead of `break`ing the loop but wanted to keep an option of using the next `console.log` statement for debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/709)

Optimize join by skipping unnecessary proposals

---

src/runtime/parser.ts

Exceptions encountered while parsing could kill the editor and put things in a bad state, this PR should prevent that from happening at all.
Related to #661 and #699 
This doesn't make error messages any better or cause these kinds of errors to provide useful feedback, but it does at least keep thing running.

prevent errors from escaping the parser

---

src/runtime/builder.ts
src/runtime/join.ts
test/join.ts

@ibdknox This is the simplest fix for lookup with missing variables (albeit not performant). Plus I've changed default index for full-scan to `ave`.
I haven't pushed any other full-scan optimizations since in this implementation missing variables won't trigger full-scan. But if full-scan will be used in other contexts (asides from `****`) then please tell me and I'll be glad to push an adaptive index support to full-scan.
Closes #685.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/715)

Lookup with missing variables

---

src/runtime/providers/string.ts
test/strings.ts

adds a `find[]` method that takes the following arguments:
- *text*: the base text to look in
- *subtext*: the text we're looking for
- *from* (optional): an index to start from
- *case-sensitive* (optional): whether or not the search should take case into account (default false)
And returns:
- *string-position*: position of the subtext in the string
- *result-index*: the index of this position in the results (e.g. 1 is the first occurrence of subtext)

add string find

---

src/client.ts
src/runtime/runtimeClient.ts

This makes it so that we load CSS when we load a program and also fixes the issue where CSS blocks aren't appropriately separated by a newline when they're concatenated together.
Fixes #704 and #703.

Fix #704 and #703

---

src/runtime/runtime.ts

A first interned object will have an id of 0. Therefore `if(!id) return` will wrongfully terminate release of it.
Also slightly faster :D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/749)

Fix Interner.release for the first interned object

---

package.json

`keyof` type is supported only since typescript 2.1
(but reliably compiles runtime.ts only since 2.1.4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/747)

Fix a required typescript version

---

src/runtime/runtime.ts

Mostly working*
This is still busted for interesting functions (where not all fields can be sourced from the `input` change) because (I think) our scans are being too greedy about using only values from the input rather than the index thanks to `acceptInput`. I added a useless `=` function as a PoC that seems okay for filtering, and + works (so long as it meets the requirement above).
```
search
[age:age1]
[age:age2]
age1 > age2
commit
[age1 age2]
```

Refactor runtime functions

---

src/runtime/runtime.ts

This is WIP. It still requires a documentation pass.
It addresses the issues with applyInputs being either too greedy (applying to all valid scans as it did initially) or too conservative (applying to only one at a time). The method here is based on Power Sets, specifically using the neat bitflag trick of using a single iterator from 1..(N - 1) to signify the inclusiveness of the subsets.

Correctly permute all input constraints

---

index.html
src/runtime/indexes.ts
src/runtime/runtime.ts
src/systemJSConfig.js

This pulls indexes out into their own file so we can have a few different types. It also fixes a couple of show-stopping performance issues, reduces allocations a fair amount, and generally gets us into pretty good performance territory.
Before these changes the test case at the bottom took 16s, it's now ~300ms. The previous runtime couldn't do more than 3k updates (this does 10k) and hit ~75s doing so.

performance tweaks, add a hash index

---

src/runtime/runtime.ts

Currently, each time an interned number is released an extra slot is allocated in interned strings storage (with value of undefined) which won't be reclaimable and vice-versa.
Either a check on an interned value type should be added or `delete` could be used (to prevent branching while fixing the issue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/witheve/eve/750)

Fix a leak in Interner.release

---

examples/gaussian.eve
src/runtime/providers/math.ts
test/math.ts

For https://github.com/witheve/Eve/issues/631 finally.
I've gone for the more conservative option of only filtering if one or both items cannot be converted to a number. 
Let me know if you want this code to filter and I'll change
search
a = "1"
b = "2"
x = a + b
commit @browser
[#div text:x]
Which will currently set x to 3.

Fix + should not concat strings

---

src/runtime/runtime.ts

Get the interner to arena allocate ids for functions so that we don't unnecessarily accumulate them. This also sets up to be able to release IDs from removes if we think that's the right thing to do. If we do end up doing that though, we have to be aware that holding onto a change after a transaction has finished will lead to potentially unresolvable values (or worse, incorrectly resolved values).

Arena allocate function interns

---

src/runtime/dsl.ts
src/runtime/runtime.ts
test/foundation.ts

This change adds an AntiJoin node type that serves as the basis for blocks that contain a logical negation in them. It also hooks up the DSLNot node that we created and adds a simple test to show what using not looks like.

BinaryFlow and AntiJoin nodes, hookup DSL not

---

src/runtime/dsl.ts
src/runtime/runtime.ts

This PR adds basic commutative aggregates to the runtime, using `sum` as the motivating example. Right now, aggregates are going to be pretty slow and do a lot of scary crossing at the end that we will ultimately need to find a way around, but this will work for the moment.

Runtime aggregates

---

src/programs/compiler.ts
src/runtime/dsl2.ts
src/runtime/runtime.ts
src/watchers/compiler.ts
test/foundation.ts

Add the ability to call `foo.remove()` to remove all the attributes attached to a record, thus removing the record

add free AV remove and a test

---

src/watchers/dom.ts
src/watchers/editor.ts
src/watchers/html.ts

Since mouseenter and mouseleave are basically useless without each other, users should just subscribe to both at once. We've also taken the opportunity to make the subscription a little more standard. Future subscribed events will all live in the `html/listener/<event>` space.
In the off chance a user tries to use hovering on a lot of elements in their app, we've switched to mouseover/mouseout with bubbling. This leads to a lot more false positives, but only costs a single listener. Whether this is better or worse basically depends on the eve performance to browser performance ratio. In either case, it's easy to switch back if need be. We could also be a little fancier and track hover state on the elements in JS, in which case we don't need to send false events.
Finally, for convenience …

Make the hover mechanics a little more ergonomic

---

assets/css/base.css
src/runtime/dsl2.ts
src/runtime/runtime.ts
src/runtime/stdlib.ts
src/watchers/ui.ts
test/aggregate.ts
test/all.ts
test/stdlib/math.ts

Fixes:
* Debug print for AntiJoin nodes
* Correctly stratify nots and chooses when dependent
* Fix some other minor bugs in the stratifier
* Disable stratifying chooses/unions/nots after one another until systemic issues involving partial input execution can be fixed. These problems only effect certain edge cases, but we'd prefer to explicitly require users to type a bit more in the interim than risk them getting bitten by very unintuitive issues in the runtime. 
Adds:
* Support for function constraints that return multiple values using `makeMultiFunction`. This is a relatively naive implementation. If the branch in `resolveProposal`/`accept` proves to be expensive, we can easily specialize at construction time, at the cost of more lines of code. We could also have a more advanced …

Stratification bugfixes + multi-returning function constraint support

---

assets/css/editor.css
src/watchers/editor.ts
src/watchers/shape.ts

This PR should fix editor demo in eve-starter, that was broken by PR witheve/eve-starter#5 ([issue](witheve/eve-starter#4)).
I've a made a very quick test for editor, it seems to work. At least I can see rotating hexagons now, and some navigation. But you may want to test it yourself as well.

add px to units for html5 compatibility in eve-starter editor demo

---

test/aggregate.ts

**I'm not sure this PR should be merged.**
I wanted to do LIMIT queries in Eve. First I've tried `gather(…).count() <= 5`. And I was surprised to get zero results in some cases. I've even thought it's a bug in Eve. But it's not, because `0 <= 5` (obviously!).
Then I've studied the `test/` folder. And finally I've come up with: `let pos = gather(…).sort(); pos <= 5`. ~~Which works great.~~ (see my comments to this PR)
I view `test/` folder as the best example on how to use Eve query language. That's why I'm adding "limit query" test there.
(I've also renamed some blocks in `test/aggregate.ts`.)

Test that shows how to emulate LIMIT queries

---

package.json
src/programs/perfReport.ts
src/runtime/dsl2.ts
src/runtime/performance.ts
src/types.d.ts
src/watchers/canvas.ts
src/watchers/dom.ts
src/watchers/html.ts
src/watchers/tag-browser.ts
src/watchers/ui.ts
src/watchers/watcher.ts

This replaces [deprecated `node-uuid`](https://www.npmjs.com/package/node-uuid) package with [`uuid`](https://www.npmjs.com/package/uuid).
As a bonus, it shaves 92K from my app webpack bundle:
|   Filename      | before           | after  |
| :------------- |-------------:| -----:|
| main.js     | 1.2M | 649K |
| main.min.js      | 554K      |   271K |
| main.min.js.gz | 164K      |    72K |
It's because `node-uuid` was bringing huge amount of crypto packages with it.

Switch off from deprecated node-uuid package

---

package.json
src/parser/parser.ts

The way tokens are exposed seems to have changed fundamentally, which broke parsing.

Hotfix: use tokenMatcher from chevrotain to determine tokenType

---

src/parser/parser.ts

This implements part of the feature request in #436. It adds a slightly friendlier error message that appears when a value without an attribute in a record. For example, this code
```
search
twenty = [-20]
bind
[#ui/text text: twenty]
```
will generate the error message `"-20" needs to be labeled with an attribute`.
After this, the `attribute` rule could be modified to take another argument specifying whether the record that is being parsed is part of a `functionRecord`. If so, the message could mention that function syntax requires arguments to be labeled, and include parameter names if it is a standard library function. I can work on that next, if this looks good to you.

Add a custom error message for values without attributes in a record

---

src/watchers/dom.ts
src/watchers/html.ts
src/watchers/svg.ts

* Enables using `html.addExternalRoot()` to control SVG placement
* Enables mixing SVG into html documents, a feature I'd embarrassingly forgotten that the previous SVG library lacked.
* This fix is robust, but the original DOM library abstraction is really creaking here, it's worth revisiting in the future. This is especially the case since UI performance can be easily improved by an order of magnitude or more by not mirroring the instances back into Eve. In 0.4, this isn't really an issue, but 0.3 could really benefit from the boost.

quickfix to delegate svg/root to the html watcher like canvas

---

src/runtime/dsl2.ts

Program.inputEAVs throws an exception when the input eav array is empty, so Program.load shouldn't call it when no code blocks are returned from parsing the document.

Prevent exception from program which parses to no code blocks

---

src/watchers/compiler.ts

Debug printing was preventing native Eve program compilation in headless mode because `groupCollapsed()` is not a defined function in that context.

only group console logs if possible

---

src/watchers/watcher.ts

Let's you write
``` typescript
let eavs = appendAsEAVs([], {tag: "parent", name: "fred", children: [
{tag: "child", name: "bruce"},
{tag: "pet", name: "betsy"}
]});
```
along with the previously supported
``` typescript
let eavs = appendAsEAVs([], {tag: "parent", name: "fred", children: [].concat(
appendAsEAVs([], {tag: "child", name: "bruce"}),
appendAsEAVs([], {tag: "pet", name: "betsy"})
)});
```

Allow appendAsEAVs to also handle nested sub-records and sub-record sets

---

assets/css/base.css

Given that not all users who want the default styling will be using the starter, it makes more sense to ship watcher CSS as part of the runtime repo.

More first party watcher CSS into witheve/eve rather than the starter

---

src/ide.ts

Fixed title text for collapse/expand sidebar button.

---

.gitignore
assets/css/dialog.css
assets/css/matchesonscrollbar.css
index.html
src/dialog.js
src/matchesonscrollbar.js
src/search.js
src/searchcursor.js

Added the search function using codemirror's add-ons, as per issue #799.

Add search
